name: Build

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
